Vagrant.configure("2") do |config|

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
	web01.vm.network "private_network", ip: "192.168.20.12"
	web01.vm.provider "virtualbox" do |vb|
     vb.cpus = 2
     vb.memory = "1024"
   end
   web01.vm.provision "shell", inline: <<-SHELL
	 apt update 
     apt install apache2 wget unzip -y
	 systemctl start httpd
	 systemctl enable httpd
	 cd /tmp/
	 wget https://www.tooplate.com/zip-templates/2124_vertex.zip
	 unzip -o 2124_vertex.zip
	 cp -r 2124_vertex/* /var/www/html/
     systemctl restart httpd
   SHELL
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
	db01.vm.network "private_network", ip: "192.168.20.15"
	db01.vm.provider "virtualbox" do |vb|
     vb.cpus = 2
     vb.memory = "1024"
   end
   db01.vm.provision "shell", inline: <<-SHELL
	 yum install mariadb-server -y
	 systemctl start mariadb-server
     systemctl enable mariadb-server
	 
	 mysql -u root -e 'CREATE DATABASE wordpress;'
	 mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost IDENTIFIED BY "admin123";'
	 mysql -u root -e 'FLUSH PRIVILEGES;'
   SHELL
  end
end